from noc_cli.setup import build_env_lines


def test_build_env_lines_produces_key_equals_value_pairs():
    answers = {
        "ZENDESK_SUBDOMAIN": "carbyne",
        "ZENDESK_EMAIL": "analyst@carbyne.com",
        "ZENDESK_API_TOKEN": "tok-abc123",
        "NOC_TICKETS_ROOT": "/Users/analyst/Tickets",
        "NOC_OWNER": "analyst",
        "NOC_WATCH_VIEW": "888",
        "NOC_WATCH_ASSIGNEE": "analyst@carbyne.com",
        "NOC_NOTIFY": "banner,ping",
    }
    lines = build_env_lines(answers)
    assert "ZENDESK_SUBDOMAIN=carbyne" in lines
    assert "ZENDESK_EMAIL=analyst@carbyne.com" in lines
    assert "ZENDESK_API_TOKEN=tok-abc123" in lines
    assert "NOC_TICKETS_ROOT=/Users/analyst/Tickets" in lines
    assert "NOC_OWNER=analyst" in lines
    assert "NOC_WATCH_VIEW=888" in lines
    assert "NOC_WATCH_ASSIGNEE=analyst@carbyne.com" in lines
    assert "NOC_NOTIFY=banner,ping" in lines
    assert lines.startswith("# Generated by noc-cli setup")


def test_build_env_lines_skips_empty_values():
    answers = {
        "ZENDESK_SUBDOMAIN": "carbyne",
        "NOC_WATCH_VIEW": "",        # optional — not yet configured
        "NOC_WATCH_ASSIGNEE": "",    # optional — not yet configured
    }
    lines = build_env_lines(answers)
    assert "ZENDESK_SUBDOMAIN=carbyne" in lines
    assert "NOC_WATCH_VIEW" not in lines
    assert "NOC_WATCH_ASSIGNEE" not in lines


def test_build_env_lines_quotes_values_with_spaces():
    answers = {
        "NOC_TICKETS_ROOT": "/Users/My Analyst/Tickets",
    }
    lines = build_env_lines(answers)
    assert 'NOC_TICKETS_ROOT="/Users/My Analyst/Tickets"' in lines


def test_build_env_lines_quotes_values_with_hash():
    answers = {
        "ZENDESK_API_TOKEN": "tok#weird",
    }
    lines = build_env_lines(answers)
    assert 'ZENDESK_API_TOKEN="tok#weird"' in lines


def test_build_env_lines_preserves_key_order():
    answers = {
        "ZENDESK_SUBDOMAIN": "carbyne",
        "ZENDESK_EMAIL": "a@b.com",
        "ZENDESK_API_TOKEN": "tok",
        "NOC_OWNER": "alice",
    }
    lines = build_env_lines(answers)
    pos_sub = lines.index("ZENDESK_SUBDOMAIN")
    pos_email = lines.index("ZENDESK_EMAIL")
    pos_tok = lines.index("ZENDESK_API_TOKEN")
    pos_owner = lines.index("NOC_OWNER")
    assert pos_sub < pos_email < pos_tok < pos_owner


def test_build_env_lines_emits_unquoted_when_value_has_quote_but_no_space_or_hash():
    # A double-quote alone (no space, no '#') does not trigger quoting — document that.
    answers = {"ZENDESK_API_TOKEN": 'tok"x'}
    lines = build_env_lines(answers)
    assert 'ZENDESK_API_TOKEN=tok"x' in lines


def test_build_env_lines_handles_empty_and_all_empty_dicts():
    # Empty dict and all-empty-values dict return only the header — no bare '=' line.
    assert build_env_lines({}).startswith("# Generated by noc-cli setup")
    only_empty = build_env_lines({"K": ""})
    assert only_empty.startswith("# Generated by noc-cli setup")
    assert "K=" not in only_empty
    assert "=\n" not in only_empty  # no stray bare-key line
