from noc_cli import config


def test_data_dir_respects_noc_home(monkeypatch, tmp_path):
    monkeypatch.setenv("NOC_HOME", str(tmp_path))
    assert config.data_dir() == tmp_path


def test_load_config_reads_env_file(monkeypatch, tmp_path):
    monkeypatch.setenv("NOC_HOME", str(tmp_path))
    monkeypatch.delenv("ZENDESK_SUBDOMAIN", raising=False)
    monkeypatch.delenv("NOC_OWNER", raising=False)
    (tmp_path / ".env").write_text("ZENDESK_SUBDOMAIN=carbyne\nNOC_OWNER=alice\n")
    cfg = config.load_config()
    assert cfg.zendesk_subdomain == "carbyne"
    assert cfg.owner == "alice"
    assert cfg.zendesk_base_url == "https://carbyne.zendesk.com/api/v2"


def test_process_env_overrides_file(monkeypatch, tmp_path):
    monkeypatch.setenv("NOC_HOME", str(tmp_path))
    (tmp_path / ".env").write_text("ZENDESK_SUBDOMAIN=fromfile\n")
    monkeypatch.setenv("ZENDESK_SUBDOMAIN", "fromenv")
    cfg = config.load_config()
    assert cfg.zendesk_subdomain == "fromenv"


def test_valid_config_keys_returns_editable_field_names():
    assert config.valid_config_keys() == [
        "zendesk_subdomain",
        "zendesk_email",
        "zendesk_api_token",
        "tickets_root",
        "owner",
        "watch_view",
        "watch_assignee",
        "notify",
        "timezone",
    ]


def test_set_config_value_preserves_siblings_in_canonical_order(monkeypatch, tmp_path):
    monkeypatch.setenv("NOC_HOME", str(tmp_path))
    (tmp_path / ".env").write_text(
        "NOC_NOTIFY=terminal\n"
        "NOC_WATCH_ASSIGNEE=alice@carbyne.com\n"
        "ZENDESK_EMAIL=old@carbyne.com\n"
    )

    config.set_config_value("watch_assignee", "bob@carbyne.com")

    assert (tmp_path / ".env").read_text() == "\n".join([
        "# Generated by noc-cli setup",
        "",
        "ZENDESK_EMAIL=old@carbyne.com",
        "NOC_WATCH_ASSIGNEE=bob@carbyne.com",
        "NOC_NOTIFY=terminal",
        "",
    ])


def test_set_config_value_creates_absent_env_file(monkeypatch, tmp_path):
    monkeypatch.setenv("NOC_HOME", str(tmp_path / "noc-home"))

    config.set_config_value("watch_view", "12345")

    env_file = tmp_path / "noc-home" / ".env"
    assert env_file.exists()
    assert env_file.read_text() == "\n".join([
        "# Generated by noc-cli setup",
        "",
        "NOC_WATCH_VIEW=12345",
        "",
    ])


def test_set_config_value_reads_file_not_process_env(monkeypatch, tmp_path):
    monkeypatch.setenv("NOC_HOME", str(tmp_path))
    monkeypatch.setenv("ZENDESK_EMAIL", "env@carbyne.com")

    config.set_config_value("owner", "alice")

    text = (tmp_path / ".env").read_text()
    assert "NOC_OWNER=alice" in text
    assert "ZENDESK_EMAIL" not in text


def test_set_config_value_rejects_unknown_key_with_valid_keys(monkeypatch, tmp_path):
    monkeypatch.setenv("NOC_HOME", str(tmp_path))

    try:
        config.set_config_value("not_real", "value")
    except KeyError as exc:
        message = str(exc)
    else:
        raise AssertionError("set_config_value should reject unknown keys")

    assert "not_real" in message
    assert "zendesk_email" in message
    assert "watch_assignee" in message
