from pathlib import Path

from noc_cli.config import Config
from noc_cli.setup import build_env_lines, run_setup


def _make_config(**kwargs) -> Config:
    """Return a Config with all optional string fields defaulted to empty."""
    defaults = dict(
        zendesk_subdomain="",
        zendesk_email="",
        zendesk_api_token="",
        tickets_root=Path("/tmp/Tickets"),
        owner="",
        watch_view="",
        watch_assignee="",
        notify="banner,ping",
    )
    defaults.update(kwargs)
    return Config(**defaults)


def test_build_env_lines_produces_key_equals_value_pairs():
    answers = {
        "ZENDESK_SUBDOMAIN": "carbyne",
        "ZENDESK_EMAIL": "analyst@carbyne.com",
        "ZENDESK_API_TOKEN": "tok-abc123",
        "NOC_TICKETS_ROOT": "/Users/analyst/Tickets",
        "NOC_OWNER": "analyst",
        "NOC_WATCH_VIEW": "888",
        "NOC_WATCH_ASSIGNEE": "analyst@carbyne.com",
        "NOC_NOTIFY": "banner,ping",
    }
    lines = build_env_lines(answers)
    assert "ZENDESK_SUBDOMAIN=carbyne" in lines
    assert "ZENDESK_EMAIL=analyst@carbyne.com" in lines
    assert "ZENDESK_API_TOKEN=tok-abc123" in lines
    assert "NOC_TICKETS_ROOT=/Users/analyst/Tickets" in lines
    assert "NOC_OWNER=analyst" in lines
    assert "NOC_WATCH_VIEW=888" in lines
    assert "NOC_WATCH_ASSIGNEE=analyst@carbyne.com" in lines
    assert "NOC_NOTIFY=banner,ping" in lines
    assert lines.startswith("# Generated by noc-cli setup")


def test_build_env_lines_skips_empty_values():
    answers = {
        "ZENDESK_SUBDOMAIN": "carbyne",
        "NOC_WATCH_VIEW": "",  # optional — not yet configured
        "NOC_WATCH_ASSIGNEE": "",  # optional — not yet configured
    }
    lines = build_env_lines(answers)
    assert "ZENDESK_SUBDOMAIN=carbyne" in lines
    assert "NOC_WATCH_VIEW" not in lines
    assert "NOC_WATCH_ASSIGNEE" not in lines


def test_build_env_lines_quotes_values_with_spaces():
    answers = {
        "NOC_TICKETS_ROOT": "/Users/My Analyst/Tickets",
    }
    lines = build_env_lines(answers)
    assert 'NOC_TICKETS_ROOT="/Users/My Analyst/Tickets"' in lines


def test_build_env_lines_quotes_values_with_hash():
    answers = {
        "ZENDESK_API_TOKEN": "tok#weird",
    }
    lines = build_env_lines(answers)
    assert 'ZENDESK_API_TOKEN="tok#weird"' in lines


def test_build_env_lines_preserves_key_order():
    answers = {
        "ZENDESK_SUBDOMAIN": "carbyne",
        "ZENDESK_EMAIL": "a@b.com",
        "ZENDESK_API_TOKEN": "tok",
        "NOC_OWNER": "alice",
    }
    lines = build_env_lines(answers)
    pos_sub = lines.index("ZENDESK_SUBDOMAIN")
    pos_email = lines.index("ZENDESK_EMAIL")
    pos_tok = lines.index("ZENDESK_API_TOKEN")
    pos_owner = lines.index("NOC_OWNER")
    assert pos_sub < pos_email < pos_tok < pos_owner


def test_build_env_lines_emits_unquoted_when_value_has_quote_but_no_space_or_hash():
    # A double-quote alone (no space, no '#') does not trigger quoting — document that.
    answers = {"ZENDESK_API_TOKEN": 'tok"x'}
    lines = build_env_lines(answers)
    assert 'ZENDESK_API_TOKEN=tok"x' in lines


def test_build_env_lines_handles_empty_and_all_empty_dicts():
    # Empty dict and all-empty-values dict return only the header — no bare '=' line.
    assert build_env_lines({}).startswith("# Generated by noc-cli setup")
    only_empty = build_env_lines({"K": ""})
    assert only_empty.startswith("# Generated by noc-cli setup")
    assert "K=" not in only_empty
    assert "=\n" not in only_empty  # no stray bare-key line


def test_run_setup_writes_env_file_from_answers(tmp_path, monkeypatch):
    monkeypatch.setenv("NOC_HOME", str(tmp_path))
    monkeypatch.setenv("USER", "alice")
    env_path = tmp_path / ".env"
    existing = _make_config()

    answers = iter(
        [
            "carbyne",  # Zendesk subdomain
            "alice@carbyne.com",  # Zendesk email
            "tok-secret",  # Zendesk API token
            str(tmp_path / "Tickets"),  # NOC_TICKETS_ROOT
            "alice",  # NOC_OWNER
            "777",  # NOC_WATCH_VIEW
            "alice@carbyne.com",  # NOC_WATCH_ASSIGNEE
            "banner,ping",  # NOC_NOTIFY
        ]
    )

    def fake_prompt(label: str, default: str = "", hide_input: bool = False) -> str:
        return next(answers)

    run_setup(env_path, existing, prompt_fn=fake_prompt)

    assert env_path.exists()
    text = env_path.read_text()
    assert "ZENDESK_SUBDOMAIN=carbyne" in text
    assert "ZENDESK_EMAIL=alice@carbyne.com" in text
    assert "ZENDESK_API_TOKEN=tok-secret" in text
    assert "NOC_OWNER=alice" in text
    assert "NOC_WATCH_VIEW=777" in text
    assert "NOC_WATCH_ASSIGNEE=alice@carbyne.com" in text
    assert "NOC_NOTIFY=banner,ping" in text


def test_run_setup_uses_existing_values_as_defaults(tmp_path, monkeypatch):
    monkeypatch.setenv("NOC_HOME", str(tmp_path))
    monkeypatch.setenv("USER", "bob")
    env_path = tmp_path / ".env"
    existing = _make_config(
        zendesk_subdomain="prevdomain",
        zendesk_email="prev@x.com",
        zendesk_api_token="prev-tok",
        tickets_root=tmp_path / "OldTickets",
        owner="bob",
        watch_view="999",
        watch_assignee="prev@x.com",
        notify="banner,ping",
    )

    defaults_received: list[str] = []

    def capture_default(label: str, default: str = "", hide_input: bool = False) -> str:
        defaults_received.append(default)
        return default  # simulate pressing Enter

    run_setup(env_path, existing, prompt_fn=capture_default)

    assert defaults_received[0] == "prevdomain"  # subdomain default
    assert defaults_received[1] == "prev@x.com"  # email default
    # index 2 is the token — hide_input=True; default still provided but masked
    assert defaults_received[4] == "bob"  # owner default
    assert defaults_received[5] == "999"  # watch_view default
    assert defaults_received[6] == "prev@x.com"  # watch_assignee default

    text = env_path.read_text()
    assert "ZENDESK_SUBDOMAIN=prevdomain" in text


def test_run_setup_creates_data_dir_if_missing(tmp_path, monkeypatch):
    monkeypatch.setenv("NOC_HOME", str(tmp_path))
    nested = tmp_path / "deep" / "subdir"
    env_path = nested / ".env"
    existing = _make_config()

    answers = iter(
        [
            "carbyne",
            "a@b.com",
            "tok",
            str(tmp_path / "Tickets"),
            "alice",
            "",
            "",  # watch_view and watch_assignee left blank (optional)
            "banner,ping",
        ]
    )

    def fake_prompt(label: str, default: str = "", hide_input: bool = False) -> str:
        return next(answers)

    run_setup(env_path, existing, prompt_fn=fake_prompt)

    assert env_path.exists()


def test_run_setup_omits_blank_optional_watch_fields(tmp_path, monkeypatch):
    monkeypatch.setenv("NOC_HOME", str(tmp_path))
    env_path = tmp_path / ".env"
    existing = _make_config()

    answers = iter(
        [
            "carbyne",
            "a@b.com",
            "tok",
            str(tmp_path / "Tickets"),
            "alice",
            "",  # watch_view blank
            "",  # watch_assignee blank
            "banner,ping",
        ]
    )

    def fake_prompt(label: str, default: str = "", hide_input: bool = False) -> str:
        return next(answers)

    run_setup(env_path, existing, prompt_fn=fake_prompt)

    text = env_path.read_text()
    assert "NOC_WATCH_VIEW" not in text
    assert "NOC_WATCH_ASSIGNEE" not in text
