"""noc-cli setup wizard — pure logic layer.

The `build_env_lines` function is a pure serialiser; no I/O.
`run_setup` orchestrates the interactive wizard but accepts all
side-effecting operations (prompt function, path) as arguments so
it can be driven in tests without real stdin, real filesystem writes,
or the real home directory.
"""
from __future__ import annotations


def build_env_lines(answers: dict[str, str]) -> str:
    """Serialise wizard answers to a `.env`-format string.

    Rules (mirrors the sister Rust app's write_env_file):
    - Skips keys whose value is the empty string (optional fields not yet set).
    - Quotes values that contain a space or '#' with double-quotes.
    - Preserves insertion order (dict is ordered in Python 3.7+).
    - Prepends a generated-by header comment.
    """
    lines: list[str] = ["# Generated by noc-cli setup", ""]
    for key, value in answers.items():
        if not value:
            continue
        needs_quote = " " in value or "#" in value
        if needs_quote:
            lines.append(f'{key}="{value}"')
        else:
            lines.append(f"{key}={value}")
    lines.append("")  # trailing newline
    return "\n".join(lines)
